System Health Node
shadow-robot/sr_utils pull request #18
Opened 2022-06-07 16:21 UTC by jeferrandiz98

## Proposed changes

Implementation of a system health node useful for benchmarking.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [x] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-06-08 10:35 UTC, maxzieba requested changes

2022-06-08 10:35 UTC, maxzieba commented on sr_system_health/src/sr_system_health/system_health.py
> +# Copyright 2021 Shadow Robot Company Ltd.
2022

2022-06-08 10:53 UTC, biofotis requested changes

2022-06-08 10:53 UTC, biofotis commented on sr_system_health/CMakeLists.txt
> +catkin_install_python(PROGRAMS src/sr_system_health/system_health.py
Can you please do it like here? https://github.com/shadow-robot/sr_teleop_internal/blob/noetic-devel/sr_teleop_mock/CMakeLists.txt#L160

2022-06-09 09:57 UTC, maxzieba approved these changes

2022-06-21 09:23 UTC, biofotis approved these changes

2022-06-21 09:23 UTC, biofotis approved these changes

2022-06-21 09:23 UTC, merged