F adding libraries from shadow r ethercat
shadow-robot/sr_utils pull request #4
Opened 2019-07-23 07:22 UTC by mikramarc

2019-07-24 12:01 UTC, beatrizleon approved these changes

2019-09-17 12:12 UTC, toliver requested changes

2019-09-17 12:12 UTC, toliver commented on sr_interpolation/package.xml
> +  <author email="yi@shadowrobot.com">Yi Li</author>
Please remove these two authors.

2019-09-17 16:29 UTC, toliver approved these changes

2019-09-17 16:29 UTC, merged